"""Pydantic 数据模型（Schema）"""
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserInDB,
    Token,
    TokenPayload,
    LoginRequest,
    PasswordChange,
    PasswordResetRequest,
    PasswordReset,
)
from app.schemas.subscription import (
    SubscriptionBase,
    SubscriptionCreate,
    SubscriptionUpdate,
    SubscriptionResponse,
    SubscriptionDetailResponse,
    SubscriptionWithPaymentResponse,
    PlanInfo,
    PlanListResponse,
    SubscriptionPlan,
    SubscriptionStatus,
    PLAN_CONFIG,
)
from app.schemas.order import (
    OrderBase,
    OrderCreate,
    OrderUpdate,
    OrderCancel,
    OrderResponse,
    OrderDetailResponse,
    OrderListResponse,
    OrderStatus,
    OrderItem,
    ShippingAddress,
)
from app.schemas.payment import (
    PaymentBase,
    PaymentCreate,
    AlipayPaymentRequest,
    PaymentCallback,
    PaymentResponse,
    PaymentStatusResponse,
    AlipayPayUrlResponse,
    PaymentResult,
    PaymentStatus,
    PaymentProvider,
)

__all__ = [
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "Token",
    "TokenPayload",
    "LoginRequest",
    "PasswordChange",
    "PasswordResetRequest",
    "PasswordReset",
    # Subscription
    "SubscriptionBase",
    "SubscriptionCreate",
    "SubscriptionUpdate",
    "SubscriptionResponse",
    "SubscriptionDetailResponse",
    "SubscriptionWithPaymentResponse",
    "PlanInfo",
    "PlanListResponse",
    "SubscriptionPlan",
    "SubscriptionStatus",
    "PLAN_CONFIG",
    # Order
    "OrderBase",
    "OrderCreate",
    "OrderUpdate",
    "OrderCancel",
    "OrderResponse",
    "OrderDetailResponse",
    "OrderListResponse",
    "OrderStatus",
    "OrderItem",
    "ShippingAddress",
    # Payment
    "PaymentBase",
    "PaymentCreate",
    "AlipayPaymentRequest",
    "PaymentCallback",
    "PaymentResponse",
    "PaymentStatusResponse",
    "AlipayPayUrlResponse",
    "PaymentResult",
    "PaymentStatus",
    "PaymentProvider",
]
